name: Code Quality
on: ["push", "pull_request"]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2  
    - name: Python Linter
      uses: sunnysid3up/python-linter@master
      with:
        source: "src"
        mypy-options: "--show-error-codes"
